// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAThhpM6uGOm6hLMbFJIx76l0ivyZSbiT8',
    appId: '1:795714982068:web:4dc00a83bfce70348f87e1',
    messagingSenderId: '795714982068',
    projectId: 'graduation-project-452806',
    authDomain: 'graduation-project-452806.firebaseapp.com',
    storageBucket: 'graduation-project-452806.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ8T6qLqxsFbD8fbmv4-pf0U4NxYvxlag',
    appId: '1:795714982068:android:1dc16859e2583b608f87e1',
    messagingSenderId: '795714982068',
    projectId: 'graduation-project-452806',
    storageBucket: 'graduation-project-452806.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3W8RjOLQX2OnXQJdxGaS9Z73_E1HJ7A0',
    appId: '1:795714982068:ios:3c6cab4898fbe4108f87e1',
    messagingSenderId: '795714982068',
    projectId: 'graduation-project-452806',
    storageBucket: 'graduation-project-452806.firebasestorage.app',
    iosClientId: '795714982068-i2tfjd5p9hteobjdc0i238gh57us8fu2.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3W8RjOLQX2OnXQJdxGaS9Z73_E1HJ7A0',
    appId: '1:795714982068:ios:3c6cab4898fbe4108f87e1',
    messagingSenderId: '795714982068',
    projectId: 'graduation-project-452806',
    storageBucket: 'graduation-project-452806.firebasestorage.app',
    iosClientId: '795714982068-i2tfjd5p9hteobjdc0i238gh57us8fu2.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAThhpM6uGOm6hLMbFJIx76l0ivyZSbiT8',
    appId: '1:795714982068:web:76312a4b8084d23c8f87e1',
    messagingSenderId: '795714982068',
    projectId: 'graduation-project-452806',
    authDomain: 'graduation-project-452806.firebaseapp.com',
    storageBucket: 'graduation-project-452806.firebasestorage.app',
  );
}
